parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $setDirectory: '%kernel.project_dir%/%env(SETS_DIRECTORY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Bywulf\Jigsawlutioner\Service\PointService: ~
